#!/usr/bin/env python3
"""Perplexity Deep Research Agent — Self-contained research agent.

Submits a research query to Perplexity, attempts to use the
"Deep Research" mode (with automatic fallback to standard search),
and saves the result as a Markdown report.

Generated by universal-agents compiler.
Edit config.json to change behavior.

Usage:
    python agent.py "What are the latest advances in fusion energy?"
    python agent.py --login                         # Capture Perplexity session
    python agent.py "Query" --visible               # Show browser
    python agent.py "Query" --mode deep             # Force Deep Research mode
    python agent.py "Query" --mode standard         # Force standard search
    python agent.py "Query" --output results/       # Custom output directory
"""

import argparse
import asyncio
import json
import logging
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent

# Make the vendored universal_agents package importable when running
# agent.py standalone from inside python-agent/.
# The entire universal_agents/ tree (browser/, core/, providers/pplx/)
# is bundled alongside this file — see DEVELOPMENT-PLAN.md §5 Unit 1.
sys.path.insert(0, str(SCRIPT_DIR))

# ---------------------------------------------------------------------------
# Load config
# ---------------------------------------------------------------------------
with open(SCRIPT_DIR / "config.json", encoding="utf-8") as f:
    CONFIG = json.load(f)

_kwargs = dict(CONFIG["config_kwargs"])

# Resolve storage state relative to package
_state = SCRIPT_DIR / "storage" / "pplx_storage_state.json"
if _state.exists():
    _kwargs["storage_state"] = str(_state)

_research_cfg = CONFIG.get("research", {})
OUTPUT_DIR = SCRIPT_DIR / _research_cfg.get("output_dir", "reports/")
MAX_WAIT = _research_cfg.get("max_research_wait", 300)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Imports
# ---------------------------------------------------------------------------
from universal_agents.providers.pplx.config import PerplexityResearchConfig
from universal_agents.providers.pplx.research import PerplexityResearchAgent
from universal_agents.providers.pplx.selectors import LOGIN_INDICATOR_NEGATIVE


# ---------------------------------------------------------------------------
# Login helpers
# ---------------------------------------------------------------------------

async def _has_visible_login_button(page) -> bool:
    """Return ``True`` if a login / sign-up button or link is currently visible.

    Mirrors the negative-detection loop in
    :meth:`PerplexityResearchAgent.check_logged_in`.
    """
    for selector in LOGIN_INDICATOR_NEGATIVE:
        try:
            for el in await page.locator(selector).all():
                if not await el.is_visible():
                    continue
                text = (await el.inner_text()).strip().lower()
                if any(p in text for p in ("log in", "sign up", "sign in")):
                    return True
        except Exception:
            continue
    return False


async def capture_login() -> bool:
    """Open a visible browser so the user can log in to Perplexity.

    Auto-detects successful login by polling the DOM every 5 s.
    Uses **strict** login detection so the browser never closes prematurely
    (unlike the lenient default which can assume "already logged in" on a
    freshly-loaded page where no DOM indicators have rendered yet).

    Detection is robust even against unverified positive selectors: login
    success is also declared when the negative indicators (login/sign-up
    buttons) that were visible at page load **disappear**, which reliably
    indicates a completed login flow.

    No stdin interaction needed — this runs cleanly under opencode shell-out.
    """
    logger.info("Opening browser for Perplexity login...")
    config = PerplexityResearchConfig(**{**_kwargs, "headless": False})
    agent = PerplexityResearchAgent(config)

    try:
        async with agent:
            page = await agent.browser_mgr.ensure_page()

            # Navigate and wait for the page to render before any DOM checks.
            # Perplexity.ai is a heavy SPA — 2 s is not enough for login buttons
            # to appear; we wait for network idle then give an extra settle.
            await page.goto("https://www.perplexity.ai")
            try:
                await page.wait_for_load_state("networkidle", timeout=15_000)
            except Exception:
                pass
            await page.wait_for_timeout(3000)

            # Check if already logged in (e.g. from a previous session).
            # Use STRICT mode — require POSITIVE proof of login, otherwise
            # a fresh page with no DOM rendered yet falls through the lenient
            # default and closes the browser immediately.
            if await agent.check_logged_in(strict=True):
                logger.info("Already logged in!")
                await _save_storage_state(page)
                return True

            # Establish a logged-out baseline: confirm that at least one
            # negative indicator (e.g. "Log in" button) is visible.  We
            # use this later as a second success signal: when these
            # buttons *disappear* the user has completed login.
            had_login_button = await _has_visible_login_button(page)
            if not had_login_button:
                logger.warning(
                    "No login button visible on page load — page may not "
                    "have fully rendered, or the user may already be "
                    "logged in. Continuing to poll anyway."
                )

            print("\n" + "=" * 60)
            print("  PERPLEXITY LOGIN")
            print("=" * 60)
            print("  Please log in to your Perplexity account in the browser window.")
            print("  Login success will be auto-detected — no need to press Enter.")
            print("  Waiting for login (checking every 5s, up to 10 minutes)...")
            print("=" * 60 + "\n")

            # Poll for logged-in indicator — 120 attempts at 5 s = 10 minutes.
            # Two success paths:
            #   A) Positive indicator found (strict=True returns True).
            #   B) Negative indicators *disappeared* (robust; works even when
            #      the unverified positive selectors don't match).
            for attempt in range(120):
                await asyncio.sleep(5)

                # Path A — strict positive proof
                if await agent.check_logged_in(strict=True):
                    logger.info("Login detected after %ds (positive indicator)", (attempt + 1) * 5)
                    await _save_storage_state(page)
                    return True

                # Path B — negative indicators disappeared
                if had_login_button and not await _has_visible_login_button(page):
                    logger.info(
                        "Login detected after %ds (negative indicators disappeared)",
                        (attempt + 1) * 5,
                    )
                    await _save_storage_state(page)
                    return True

                if attempt % 12 == 11:  # every ~60 s
                    elapsed = (attempt + 1) * 5
                    print(f"  Still waiting for login... ({elapsed}s)")

            logger.error("Login timeout after 10 minutes")
            print("\n  Login timeout after 10 minutes. Please try again.\n")
            return False
    except Exception as exc:
        logger.error("Login capture failed: %s", exc)
        return False


async def _save_storage_state(page) -> None:
    """Persist browser storage state (cookies, localStorage) to disk."""
    storage_dir = SCRIPT_DIR / "storage"
    storage_dir.mkdir(parents=True, exist_ok=True)
    state_file = storage_dir / "pplx_storage_state.json"

    state = await page.context.storage_state()
    state_file.write_text(
        json.dumps(state, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    _kwargs["storage_state"] = str(state_file)
    logger.info("Session saved: %s", state_file)
    print(f"\n  Login detected! Session saved to {state_file}\n")


# ---------------------------------------------------------------------------
# Research
# ---------------------------------------------------------------------------

async def run_research(query: str, mode: str, output_dir: Path, visible: bool) -> int:
    """Run a single research query and save the report."""
    kwargs = dict(_kwargs)
    if visible:
        kwargs["headless"] = False
    # These keys may already be in _kwargs (from config.json); explicit args override.
    for key in ("research_mode", "output_dir", "max_research_wait"):
        kwargs.pop(key, None)

    config = PerplexityResearchConfig(
        **kwargs,
        research_mode=mode,
        output_dir=str(output_dir),
        max_research_wait=MAX_WAIT,
    )

    output_dir.mkdir(parents=True, exist_ok=True)

    async with PerplexityResearchAgent(config) as agent:
        logger.info("Researching: %s", query)
        try:
            report = await agent.research(query, save=True)
            print(f"\n{'=' * 60}")
            print(f"  Research complete ({report.mode_used} mode, {report.elapsed_seconds:.1f}s)")
            print(f"  Citations: {len(report.citations)}")
            saved_path = report.save(output_dir)
            print(f"  Report saved: {saved_path}")
            print(f"{'=' * 60}\n")
            print(report.content[:2000])
            if len(report.content) > 2000:
                print(f"\n  ... (truncated, full report in {saved_path})")
            return 0
        except Exception as exc:
            logger.error("Research failed: %s", exc)
            return 1


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Perplexity Deep Research Agent",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("query", nargs="?", help="Research query / topic")
    parser.add_argument(
        "--login", action="store_true", help="Capture Perplexity login session"
    )
    parser.add_argument(
        "--visible", action="store_true", help="Show browser window"
    )
    parser.add_argument(
        "--mode",
        choices=["deep", "standard", "auto"],
        default=None,
        help="Research mode override (default: from config.json)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output directory for reports (default: reports/)",
    )
    args = parser.parse_args()

    if args.login:
        return asyncio.run(capture_login())

    # ── Auto-login (OQ-5): if no stored session exists, run login first ──
    # Mirrors gemini agent.py lines 549-554.
    if not _state.exists():
        print("\n  No login session found. Running login first...\n")
        if not asyncio.run(capture_login()):
            print(
                "  Login failed or timed out.\n"
                "  Run `agent.py --login` to retry on a machine with a display.\n"
            )
            return 1

    if not args.query:
        parser.error("A research query is required (or use --login)")

    mode = args.mode or _kwargs.get("research_mode", "auto")
    out_dir = args.output or OUTPUT_DIR

    return asyncio.run(run_research(args.query, mode, out_dir, args.visible))


if __name__ == "__main__":
    sys.exit(main())
